-- LEVI Phase 6 PostgreSQL schema. Application access must still use tenant-scoped repositories.
CREATE TABLE IF NOT EXISTS users (
  id VARCHAR(128) PRIMARY KEY,
  email VARCHAR(320) UNIQUE,
  provider VARCHAR(32) NOT NULL DEFAULT 'email',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS profiles (
  id VARCHAR(64) PRIMARY KEY, user_id VARCHAR(128) NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
  payload JSONB NOT NULL DEFAULT '{}', created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS trades (
  id VARCHAR(64) PRIMARY KEY, user_id VARCHAR(128) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  symbol VARCHAR(32) NOT NULL, status VARCHAR(32) NOT NULL, quantity INTEGER NOT NULL, price DOUBLE PRECISION NOT NULL,
  payload JSONB NOT NULL DEFAULT '{}', created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS evidence (
  id VARCHAR(64) PRIMARY KEY, user_id VARCHAR(128) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  evidence_type VARCHAR(64) NOT NULL, source_name VARCHAR(255) NOT NULL, payload JSONB NOT NULL DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS decisions (
  id VARCHAR(64) PRIMARY KEY, user_id VARCHAR(128) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  decision_type VARCHAR(64) NOT NULL, outcome VARCHAR(64) NOT NULL, payload JSONB NOT NULL DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS audit_log (
  id VARCHAR(64) PRIMARY KEY, user_id VARCHAR(128) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  action VARCHAR(128) NOT NULL, entity_type VARCHAR(64) NOT NULL, entity_id VARCHAR(64), details JSONB NOT NULL DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS auth_sessions (
  id VARCHAR(64) PRIMARY KEY, user_id VARCHAR(128) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  token_hash VARCHAR(64) NOT NULL UNIQUE, expires_at TIMESTAMPTZ NOT NULL, revoked_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS ix_trades_user ON trades(user_id);
CREATE INDEX IF NOT EXISTS ix_evidence_user ON evidence(user_id);
CREATE INDEX IF NOT EXISTS ix_decisions_user ON decisions(user_id);
CREATE INDEX IF NOT EXISTS ix_audit_user ON audit_log(user_id);
CREATE INDEX IF NOT EXISTS ix_sessions_user ON auth_sessions(user_id);
