"""Provider-neutral authentication adapter contract."""

from typing import Protocol

from .models import AuthenticatedUser, AuthSession, OAuthProvider


class AuthProvider(Protocol):
    def signup(self, *, email: str, password: str) -> AuthSession: ...
    def login(self, *, email: str, password: str) -> AuthSession: ...
    def oauth_url(self, *, provider: OAuthProvider, redirect_to: str | None = None) -> str: ...
    def verify_token(self, access_token: str) -> AuthenticatedUser: ...
    def refresh_session(self, refresh_token: str) -> AuthSession: ...
    def revoke_session(self, access_token: str) -> None: ...
    def exchange_code(self, code: str, redirect_to: str | None = None) -> AuthSession: ...


AuthAdapter = AuthProvider
