from dataclasses import dataclass
from datetime import datetime
from enum import Enum
from typing import Protocol
from .models import BrokerOrder

class OrderStatus(str, Enum):
    WORKING="working"; FILLED="filled"; PARTIAL="partial"; REJECTED="rejected"; CANCELED="canceled"
@dataclass(frozen=True)
class Account:
    account_id:str; balance:float; buying_power:float; timestamp:datetime
@dataclass(frozen=True)
class Position:
    symbol:str; quantity:int; average_price:float; current_price:float; unrealized_pnl:float; realized_pnl:float
@dataclass(frozen=True)
class Fill:
    order_id:str; symbol:str; quantity:int; fill_price:float; fill_time:datetime; side:str
@dataclass(frozen=True)
class OrderReceipt:
    order_id:str; status:OrderStatus; symbol:str; quantity:int; limit_price:float; side:str; timestamp:datetime
class BrokerAdapter(Protocol):
    def authenticate(self, credentials:dict)->bool: ...
    def get_account(self)->Account: ...
    def get_positions(self)->list[Position]: ...
    def submit_order(self, order:BrokerOrder)->OrderReceipt: ...
    def get_order_status(self, order_id:str)->OrderStatus: ...
    def get_fills(self, order_id:str)->list[Fill]: ...
    def get_open_orders(self)->list[OrderReceipt]: ...
    def get_order_history(self)->list[OrderReceipt]: ...
    def cancel_order(self, order_id:str)->bool: ...
    def is_connected(self)->bool: ...
